import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com/" />
        <link rel="preconnect" href="https://fonts.gstatic.com/" crossOrigin="" />
        <link href="https://fonts.googleapis.com/css2?family=Fustat:wght@200..800&amp;display=swap" rel="stylesheet" />
        <link href="/css/bootstrap.min.css" rel="stylesheet" media="screen" />
        <link href="/css/slicknav.min.css" rel="stylesheet" />
        <link rel="stylesheet" href="/css/swiper-bundle.min.css" />
        <link href="/css/all.css" rel="stylesheet" media="screen" />
        <link href="/css/animate.css" rel="stylesheet" />
        <link rel="stylesheet" href="/css/magnific-popup.css" />
        <link rel="stylesheet" href="/css/mousecursor.css" />
        <link href="/css/custom.css" rel="stylesheet" media="screen" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased active-sticky-header`}
      >
        <Header />
        {children}
        <Footer />
        <Script src="/js/jquery-3.7.1.min.js"></Script>
        <Script src="/js/bootstrap.min.js"></Script>
        <Script src="/js/validator.min.js"></Script>
        <Script src="/js/jquery.slicknav.js"></Script>
        <Script src="/js/swiper-bundle.min.js"></Script>
        <Script src="/js/jquery.waypoints.min.js"></Script>
        <Script src="/js/jquery.counterup.min.js"></Script>
        <Script src="/js/isotope.min.js"></Script>
        <Script src="/js/jquery.magnific-popup.min.js"></Script>
        <Script src="/js/SmoothScroll.js"></Script>
        <Script src="/js/parallaxie.js"></Script>
        <Script src="/js/gsap.min.js"></Script>
        <Script src="/js/SplitText.js"></Script>
        <Script src="/js/ScrollTrigger.min.js"></Script>
        <Script src="/js/jquery.mb.YTPlayer.min.js"></Script>
        <Script src="/js/typed.js"></Script>
        <Script src="/js/wow.js"></Script>
        <Script src="/js/function.js"></Script>
      </body>
    </html>
  );
}
